[2025-08-10T15:29:30.445+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T15:29:30.573+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T15:29:30.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T15:29:30.579+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T15:29:30.586+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_geolocation_data> on 2025-08-09 00:00:00+00:00
[2025-08-10T15:29:30.595+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=828) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T15:29:30.593+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_geolocation_data', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpkg4ze2jd']
[2025-08-10T15:29:30.596+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask fetch_geolocation_data
[2025-08-10T15:29:30.596+0000] {standard_task_runner.py:63} INFO - Started process 830 to run task
[2025-08-10T15:29:30.641+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [running]> on host a958f78a1f45
[2025-08-10T15:29:30.718+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_geolocation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T15:29:30.719+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T15:29:32.308+0000] {logging_mixin.py:188} INFO - Geolocation data fetched successfully.
[2025-08-10T15:29:32.320+0000] {logging_mixin.py:188} INFO - Geolocation data processed into DataFrame. Shape: (100, 5)
[2025-08-10T15:29:32.329+0000] {logging_mixin.py:188} INFO - An error occurred while loading data into the database: 'Connection' object has no attribute 'commit'
[2025-08-10T15:29:32.329+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-10T15:29:32.330+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T15:29:32.339+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_geolocation_data, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T152930, end_date=20250810T152932
[2025-08-10T15:29:32.360+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-10T15:29:32.380+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-10T15:29:32.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-10T16:41:39.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T16:41:39.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:41:39.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:41:39.998+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T16:41:40.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_geolocation_data> on 2025-08-09 00:00:00+00:00
[2025-08-10T16:41:40.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_geolocation_data', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmp0awpz_k8']
[2025-08-10T16:41:40.015+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask fetch_geolocation_data
[2025-08-10T16:41:40.015+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T16:41:40.016+0000] {standard_task_runner.py:63} INFO - Started process 315 to run task
[2025-08-10T16:41:40.062+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [running]> on host 49775de909c4
[2025-08-10T16:41:40.136+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_geolocation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T16:41:40.137+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T16:41:40.865+0000] {logging_mixin.py:188} INFO - Geolocation data fetched successfully.
[2025-08-10T16:41:40.870+0000] {logging_mixin.py:188} INFO - Geolocation data processed into DataFrame. Shape: (100, 5)
[2025-08-10T16:41:40.881+0000] {logging_mixin.py:188} INFO - An error occurred while loading data into the database: 'Connection' object has no attribute 'commit'
[2025-08-10T16:41:40.881+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-10T16:41:40.881+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T16:41:40.891+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_geolocation_data, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T164139, end_date=20250810T164140
[2025-08-10T16:41:40.906+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-10T16:41:40.925+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-10T16:41:40.926+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-10T16:47:10.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T16:47:10.322+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:47:10.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [queued]>
[2025-08-10T16:47:10.328+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T16:47:10.337+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_geolocation_data> on 2025-08-09 00:00:00+00:00
[2025-08-10T16:47:10.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_geolocation_data', 'scheduled__2025-08-09T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpg54oszwg']
[2025-08-10T16:47:10.346+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask fetch_geolocation_data
[2025-08-10T16:47:10.346+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T16:47:10.346+0000] {standard_task_runner.py:63} INFO - Started process 490 to run task
[2025-08-10T16:47:10.392+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_geolocation_data scheduled__2025-08-09T00:00:00+00:00 [running]> on host 49775de909c4
[2025-08-10T16:47:10.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_geolocation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T00:00:00+00:00'
[2025-08-10T16:47:10.463+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T16:47:12.437+0000] {logging_mixin.py:188} INFO - Geolocation data fetched successfully.
[2025-08-10T16:47:12.443+0000] {logging_mixin.py:188} INFO - Geolocation data processed into DataFrame. Shape: (100, 5)
[2025-08-10T16:47:12.453+0000] {logging_mixin.py:188} INFO - An error occurred while loading data into the database: 'Connection' object has no attribute 'commit'
[2025-08-10T16:47:12.454+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-10T16:47:12.454+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T16:47:12.463+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_geolocation_data, run_id=scheduled__2025-08-09T00:00:00+00:00, execution_date=20250809T000000, start_date=20250810T164710, end_date=20250810T164712
[2025-08-10T16:47:12.509+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-10T16:47:12.529+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-10T16:47:12.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
