[2025-08-18T04:57:39.310+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T04:57:39.440+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T04:56:20.068564+00:00 [queued]>
[2025-08-18T04:57:39.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T04:56:20.068564+00:00 [queued]>
[2025-08-18T04:57:39.446+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T04:57:39.453+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_transformations> on 2025-08-18 04:56:20.068564+00:00
[2025-08-18T04:57:39.462+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3350) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-18T04:57:39.460+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'run_dbt_transformations', 'manual__2025-08-18T04:56:20.068564+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpvz3zjock']
[2025-08-18T04:57:39.462+0000] {standard_task_runner.py:63} INFO - Started process 3352 to run task
[2025-08-18T04:57:39.462+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask run_dbt_transformations
[2025-08-18T04:57:39.507+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.run_dbt_transformations manual__2025-08-18T04:56:20.068564+00:00 [running]> on host b10b13b5f146
[2025-08-18T04:57:39.593+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T04:56:20.068564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T04:56:20.068564+00:00'
[2025-08-18T04:57:39.594+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T04:57:39.603+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T04:57:39.604+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --project-dir /opt/data-engineer/weather-project/dbt/weather_dbt --profiles-dir /opt/data-engineer/weather-project/dbt/weather_dbt/.dbt']
[2025-08-18T04:57:39.614+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T04:57:41.022+0000] {subprocess.py:93} INFO - [0m04:57:41  Running with dbt=1.10.7
[2025-08-18T04:57:41.277+0000] {subprocess.py:93} INFO - [0m04:57:41  Registered adapter: postgres=1.9.0
[2025-08-18T04:57:41.483+0000] {subprocess.py:93} INFO - [0m04:57:41  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-08-18T04:57:41.483+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-08-18T04:57:41.483+0000] {subprocess.py:93} INFO - - models.dbt_date
[2025-08-18T04:57:41.608+0000] {subprocess.py:93} INFO - [0m04:57:41  Found 5 models, 2 sources, 576 macros
[2025-08-18T04:57:41.610+0000] {subprocess.py:93} INFO - [0m04:57:41
[2025-08-18T04:57:41.610+0000] {subprocess.py:93} INFO - [0m04:57:41  Concurrency: 1 threads (target='dev')
[2025-08-18T04:57:41.610+0000] {subprocess.py:93} INFO - [0m04:57:41
[2025-08-18T04:57:41.751+0000] {subprocess.py:93} INFO - [0m04:57:41  1 of 5 START sql table model dimension.dim_dates ............................... [RUN]
[2025-08-18T04:57:41.961+0000] {subprocess.py:93} INFO - [0m04:57:41  1 of 5 OK created sql table model dimension.dim_dates .......................... [[32mSELECT 1837[0m in 0.21s]
[2025-08-18T04:57:41.962+0000] {subprocess.py:93} INFO - [0m04:57:41  2 of 5 START sql table model dimension.dim_locations ........................... [RUN]
[2025-08-18T04:57:41.995+0000] {subprocess.py:93} INFO - [0m04:57:41  2 of 5 OK created sql table model dimension.dim_locations ...................... [[32mSELECT 100[0m in 0.03s]
[2025-08-18T04:57:41.996+0000] {subprocess.py:93} INFO - [0m04:57:41  3 of 5 START sql view model staging.stg_weather_data ........................... [RUN]
[2025-08-18T04:57:42.088+0000] {subprocess.py:93} INFO - [0m04:57:42  3 of 5 OK created sql view model staging.stg_weather_data ...................... [[32mCREATE VIEW[0m in 0.09s]
[2025-08-18T04:57:42.091+0000] {subprocess.py:93} INFO - [0m04:57:42  4 of 5 START sql table model marts.mart_avg_temp_by_day_of_week ................ [RUN]
[2025-08-18T04:57:42.128+0000] {subprocess.py:93} INFO - [0m04:57:42  4 of 5 OK created sql table model marts.mart_avg_temp_by_day_of_week ........... [[32mSELECT 700[0m in 0.04s]
[2025-08-18T04:57:42.130+0000] {subprocess.py:93} INFO - [0m04:57:42  5 of 5 START sql table model marts.mart_daily_weather .......................... [RUN]
[2025-08-18T04:57:42.168+0000] {subprocess.py:93} INFO - [0m04:57:42  5 of 5 OK created sql table model marts.mart_daily_weather ..................... [[32mSELECT 1700[0m in 0.04s]
[2025-08-18T04:57:42.180+0000] {subprocess.py:93} INFO - [0m04:57:42
[2025-08-18T04:57:42.180+0000] {subprocess.py:93} INFO - [0m04:57:42  Finished running 4 table models, 1 view model in 0 hours 0 minutes and 0.57 seconds (0.57s).
[2025-08-18T04:57:42.215+0000] {subprocess.py:93} INFO - [0m04:57:42
[2025-08-18T04:57:42.215+0000] {subprocess.py:93} INFO - [0m04:57:42  [32mCompleted successfully[0m
[2025-08-18T04:57:42.216+0000] {subprocess.py:93} INFO - [0m04:57:42
[2025-08-18T04:57:42.216+0000] {subprocess.py:93} INFO - [0m04:57:42  Done. PASS=5 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=5
[2025-08-18T04:57:43.775+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-18T04:57:43.776+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T04:57:43.800+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=run_dbt_transformations, run_id=manual__2025-08-18T04:56:20.068564+00:00, execution_date=20250818T045620, start_date=20250818T045739, end_date=20250818T045743
[2025-08-18T04:57:43.821+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-18T04:57:43.836+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T04:57:43.837+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
