[2025-08-10T15:42:42.786+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-10T15:42:42.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-10T15:42:40.586252+00:00 [queued]>
[2025-08-10T15:42:42.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-10T15:42:40.586252+00:00 [queued]>
[2025-08-10T15:42:42.921+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-10T15:42:42.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_geolocation_data> on 2025-08-10 15:42:40.586252+00:00
[2025-08-10T15:42:42.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_geolocation_data', 'manual__2025-08-10T15:42:40.586252+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpwzeynpxs']
[2025-08-10T15:42:42.938+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask fetch_geolocation_data
[2025-08-10T15:42:42.938+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1154) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-10T15:42:42.939+0000] {standard_task_runner.py:63} INFO - Started process 1156 to run task
[2025-08-10T15:42:42.985+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.fetch_geolocation_data manual__2025-08-10T15:42:40.586252+00:00 [running]> on host a958f78a1f45
[2025-08-10T15:42:43.059+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Hendi Irwanto' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_geolocation_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T15:42:40.586252+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T15:42:40.586252+00:00'
[2025-08-10T15:42:43.060+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-10T15:42:44.842+0000] {logging_mixin.py:188} INFO - Geolocation data fetched successfully.
[2025-08-10T15:42:44.847+0000] {logging_mixin.py:188} INFO - Geolocation data processed into DataFrame. Shape: (100, 5)
[2025-08-10T15:42:44.858+0000] {logging_mixin.py:188} INFO - An error occurred while loading data into the database: 'Connection' object has no attribute 'commit'
[2025-08-10T15:42:44.858+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-10T15:42:44.858+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-10T15:42:44.868+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_geolocation_data, run_id=manual__2025-08-10T15:42:40.586252+00:00, execution_date=20250810T154240, start_date=20250810T154242, end_date=20250810T154244
[2025-08-10T15:42:44.913+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-10T15:42:44.933+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-10T15:42:44.934+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
